# Generated by Django 4.2.4 on 2023-09-09 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='semaol',
            new_name='semail',
        ),
    ]
